const DATE_FORMAT = 'DD/MM/YYYY'
const DATE_FORMAT_WITH_UNDERLINES = 'DD_MM_YYYY'
const HOUR_FORMAT = 'HH:mm'
const DATE_HOUR_FORMAT = 'DD/MM/YYYY HH:mm'
const API_FULL_DATE_FORMAT = 'YYYY-MM-DDTHH:mm:ss'
const API_DATE_FORMAT = 'YYYY-MM-DD'
const WITHOUT_YEAR_API_FORMAT = 'MM-DD'
const WITHOUT_YEAR_DATE_FORMAT = 'DD/MM'

export {
  DATE_FORMAT,
  DATE_FORMAT_WITH_UNDERLINES,
  HOUR_FORMAT,
  DATE_HOUR_FORMAT,
  API_FULL_DATE_FORMAT,
  API_DATE_FORMAT,
  WITHOUT_YEAR_API_FORMAT,
  WITHOUT_YEAR_DATE_FORMAT,
}
