const NOTIFICATION_TYPES = {
  HEIR_INVITE: 'HEIR_INVITE',
  ACCEPTED_HEIR_INVITE: 'ACCEPTED_HEIR_INVITE',
  ACTIVATED_HERITAGE: 'ACTIVATED_HERITAGE',
  HEIR_DISINHERITANCE: 'HEIR_DISINHERITANCE',
}

export { NOTIFICATION_TYPES }
