export { Login } from './login/login.page'
export { NotFound } from './not-found/not-found.page'
export { PrivatePage } from './private-page/private-page,page'
export { HomeOwner } from './home-owner/home-owner.page'
export { HomeHeir } from './home-heir/home-heir.page'
export { UserNotConfirmed } from './user-not-confirmed/user-not-confirmed.page'
export { Begin } from './begin/begin.page'
export { Register } from './register/register.page'
