export { Login } from './login/login.page'
export { NotFound } from './not-found/not-found.page'
export { PrivatePage } from './private-page/private-page,page'
export { Home } from './home/home.page'
export { UserNotConfirmed } from './user-not-confirmed/user-not-confirmed.page'
export { Begin } from './begin/begin.page'
export { Register } from './register/register.page'
export { HeirsManagement } from './heirs-management/heirs-management.page'
